
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b"\xbbt\x1eo/q\x0c\xc7{\x92bk\x18$'P"
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,8,11,12,15,16,17,],[-8,-13,0,-9,-1,-11,-2,-3,-10,-4,-7,-12,-5,-6,]),'NEWLINE':([0,1,3,4,5,6,7,8,9,11,12,13,15,16,17,],[-8,3,-9,-1,-11,-2,-3,-10,-8,-4,-7,3,-12,-5,-6,]),'INT':([3,4,5,6,7,10,11,12,14,15,16,17,],[6,-1,-11,-2,-3,-11,-4,6,6,-12,-5,-6,]),'FLOAT':([3,4,5,6,7,10,11,12,14,15,16,17,],[7,-1,-11,-2,-3,-11,-4,7,7,-12,-5,-6,]),'}':([3,4,5,6,7,8,9,11,12,13,15,16,17,],[-9,-1,-11,-2,-3,-10,-8,-4,-7,16,-12,-5,-6,]),'{':([3,4,5,6,7,10,11,12,14,15,16,17,],[9,-1,-11,-2,-3,-11,-4,9,9,-12,-5,-6,]),'[':([3,4,5,6,7,10,11,12,14,15,16,17,],[10,-1,-11,-2,-3,-11,-4,10,10,-12,-5,-6,]),'NAME':([3,4,5,6,7,10,11,12,14,15,16,17,],[11,-1,-11,-2,-3,-11,-4,11,11,-12,-5,-6,]),'STRING':([3,4,5,6,7,10,11,12,14,15,16,17,],[4,-1,-11,-2,-3,-11,-4,4,4,-12,-5,-6,]),']':([4,6,7,10,11,14,15,16,17,],[-1,-2,-3,-11,-4,17,-12,-5,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command_list':([0,9,],[1,13,]),'command':([3,],[8,]),'atom':([3,12,14,],[5,15,15,]),'all':([0,],[2,]),'atom_list':([5,10,],[12,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> all","S'",1,None,None,None),
  ('atom -> STRING','atom',1,'p_token_atom','ccl\\runtime.py',90),
  ('atom -> INT','atom',1,'p_token_atom','ccl\\runtime.py',91),
  ('atom -> FLOAT','atom',1,'p_token_atom','ccl\\runtime.py',92),
  ('atom -> NAME','atom',1,'p_token_atom','ccl\\runtime.py',93),
  ('atom -> { command_list }','atom',3,'p_block','ccl\\runtime.py',97),
  ('atom -> [ atom_list ]','atom',3,'p_list','ccl\\runtime.py',101),
  ('command -> atom atom_list','command',2,'p_command','ccl\\runtime.py',105),
  ('command_list -> <empty>','command_list',0,'p_empty_command_list','ccl\\runtime.py',109),
  ('command_list -> command_list NEWLINE','command_list',2,'p_command_list_with_newline','ccl\\runtime.py',113),
  ('command_list -> command_list NEWLINE command','command_list',3,'p_command_list','ccl\\runtime.py',117),
  ('atom_list -> <empty>','atom_list',0,'p_empty_atom_list','ccl\\runtime.py',122),
  ('atom_list -> atom_list atom','atom_list',2,'p_atom_list','ccl\\runtime.py',126),
  ('all -> command_list','all',1,'p_all','ccl\\runtime.py',131),
]
